baseURL = "https://vjacek.github.io/"
languageCode = "en-us"
title = "Victor Jacek"
theme = 'vjacek'
buildDrafts = 'false'
publishDir = 'docs' # must be 'docs' because that's what github pages needs
relativeURLs = 'true'
pluralizeListTitles = 'false'

[markup.goldmark.renderer]
unsafe = true

[Params]
  title = 'Victor Jacek'

[Menus]
  projects = [
    {Name = "Photography Portfolio", URL = "https://victorjacekphotography.com/", weight = 1 },
    {Name = "1headline", URL = "http://1headline.com", weight = 2 },
  ]
  links = [
    {Name = "GitHub", URL = "https://github.com/vjacek/", weight = 1 },
    {Name = "LinkedIn", URL = "https://www.linkedin.com/in/victorjacek/", weight = 2 },
    {Name = "Instagram", URL = "https://www.instagram.com/victorjacekphotography/", weight = 3 },
  ]

[services]
  [services.googleAnalytics]
    ID = 'G-Y9QXKKR9SE'
